### ISSUE TITLE
Morning session code review

### ISSUE THREAD

**Issue by adamteddychang** [Meri-MG/Awesome-Books-jsObjects#1]
- Since the project is incomplete, I will just point out the remaining things you should do to complete the project. 
- You will need to remove the specified item from the array as well while removing it from the UI
- It will be better if there are no preloaded books before the user starts using it. 
- You will have to complete the localStorage portion of the project. 
- Good luck! 
-

**Comment by Meri-MG** [comment]
Thanks for bringing up these issues.
- The project is completed.
- The items were removed from the array and UI.
- No preloaded books are present for the user.
- The local storage function was added to the project.
