### ISSUE TITLE
Morning session code review

### ISSUE THREAD

**Issue by adamteddychang** [Meri-MG/Awesome-Books-jsObjects#8]
Great job on almost finishing the project, there are just a few things you can add. 
- It will be better if you have a footer in your application, it will be better for the structure of the page. 
- It will be nice if you make the nav item a different color while on the page that correlates to the nav item, to convey the page that the user is on.

**Comment by Meri-MG** [comment]
Thanks for bringing up these issues.
- `<footer>` was added to the page.
- `<nav>` links are highlighted according to the user's current position on the page.
