### ISSUE TITLE
Formatting HTML Tags

### ISSUE THREAD

**Issue by uzairali19** [Meri-MG/Awesome-Books-jsObjects#9]
# Index.html

The file contains javascript `script` tags in the `<head>` tag. It would be better to see them at the bottom of the `<body> tag. 
This enables the page to load CSS and HTML elements before loading the javascript components.

**Comment by Meri-MG** [comment]
Thanks for bringing up this issue.
- Javascript script tags were removed from `<head>` tag and placed at the closing `<body>` tag
